Repository storybookjs/addon-styling, pull requests merged in 2023-04, with the labels that each got.

#24 Update docs to specify storybook version
  README.md
  auto.config.js
Labels: documentation

#25 Upgrade to storybook 7
  .babelrc.js
  .github/workflows/release.yml
  .storybook/local-preset.js
  .storybook/main.js
  .storybook/main.ts
  .storybook/preview.js
  .storybook/preview.ts
  README.md
  auto.config.js
  package.json
  preset.js
  src/decorators/class-name.strategy.tsx
  src/decorators/data-attribute.strategy.tsx
  src/decorators/helpers.ts
  src/decorators/provider.strategy.tsx
  src/index.ts
  src/manager.ts
  src/preset.ts
  src/preset/preview.ts
  src/preview.ts
  src/webpack/css/webpack.ts
  src/webpack/scss/webpack.ts
  src/webpack/types.ts
  src/webpack/webpackFinal.ts
  stories/Button.jsx
  stories/Button.stories.js
  stories/Header.jsx
  stories/Header.stories.js
  stories/Page.jsx
  stories/Page.stories.js
  tsconfig.json
  tsup.config.js
  vite.config.js
  yarn.lock
Labels: major

#30 Replace imports for decorators with ones that match the current exports.
  docs/api.md
Labels: documentation

#31 Add Less support
  README.md
  docs/api.md
  package.json
  src/preset.ts
  src/types.ts
  src/vite/viteFinal.ts
  src/webpack/css/webpack.ts
  src/webpack/less/webpack.ts
  src/webpack/types.ts
  src/webpack/webpackFinal.ts
  yarn.lock
Labels: patch
